create table if not exists world_chat (
  id bigint generated by default as identity primary key,
  content text not null,
  sender_id uuid references auth.users not null,
  username text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table world_chat enable row level security;

create policy "Public read access"
  on world_chat for select
  using ( true );

create policy "Authenticated users can insert"
  on world_chat for insert
  with check ( auth.uid() = sender_id );

-- Enable Realtime
alter publication supabase_realtime add table world_chat;
