-- Create Direct Messages Table
create table if not exists direct_messages (
  id bigint generated by default as identity primary key,
  content text not null,
  sender_id uuid references auth.users(id) not null,
  recipient_id uuid references auth.users(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS Policies (Optional but recommended)
alter table direct_messages enable row level security;

create policy "Users can view their own messages"
on direct_messages for select
using (auth.uid() = sender_id or auth.uid() = recipient_id);

create policy "Users can insert messages"
on direct_messages for insert
with check (auth.uid() = sender_id);
